# -*- coding: utf-8 -*-
"""Damos-lhe as boas-vindas ao Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# trabalho computacional
"""

a=sorted([[202614116,(5.5+4.5+8+9.5)/4],[202614190,(6.2+8.1+9.2+9)/4],[199214083,8.2]],key=lambda x:x[1],reverse=True)
print(*[f"{i+1}º Lugar - CR: {x[1]:.2f}" for i,x in enumerate(a)],f"\nMaior CR: Matrícula {a[0][0]}",sep="\n")