# -*- coding: utf-8 -*-
"""Damos-lhe as boas-vindas ao Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# trabalho computacional
"""

# Dados dos alunos
alunos = [
    {
        "matricula": 202614116,
        "nome": "Lucas",
        "quimica": 5.5,
        "geometria_analitica": 4.5,
        "pensamento_computacional": 8.0,
        "pre_calculo": 9.5
    },
    {
        "matricula": 202614190,
        "nome": "Guilherme",
        "quimica": 6.2,
        "geometria_analitica": 8.1,
        "pensamento_computacional": 9.2,
        "pre_calculo": 9.0
    }
]

# Calcula o CR dos alunos A e B
for aluno in alunos:
    aluno["CR"] = (
        aluno["quimica"] +
        aluno["geometria_analitica"] +
        aluno["pensamento_computacional"] +
        aluno["pre_calculo"]
    ) / 4

# Adiciona o aluno C com CR informado
alunos.append({
    "matricula": 199214083,
    "nome": "Marcos",
    "CR": 8.2
})

# Ranking por CR
ranking = sorted(alunos, key=lambda x: x["CR"], reverse=True)

print("===== RANKING DOS ALUNOS =====\n")

for posicao, aluno in enumerate(ranking, start=1):
    print(f"{posicao}º Lugar - CR: {aluno['CR']:.2f}")

# Maior CR
maior_cr = ranking[0]

print("\n===== RESULTADO FINAL =====")
print(f"A matrícula com o maior CR é {maior_cr['matricula']} (CR = {maior_cr['CR']:.2f}).")